version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  ApplicationStart:
    - location: codedeploy/ApplicationStart.sh
  ApplicationStop:
    - location: codedeploy/ApplicationStop.sh