version: 0.0
os: linux
files:
  - source: /main.go
    destination: /app/
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: root
  Install:
    - location: scripts/install.sh 
      timeout: 180
      runas: root